# Generated by Django 6.0.7 on 2026-07-13 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        ('threats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='threats',
            field=models.ManyToManyField(blank=True, related_name='events', to='threats.threat'),
        ),
    ]
