# Generated by Django 6.0.7 on 2026-07-13 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_threats'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='risk_level',
            field=models.CharField(choices=[('LOW', 'Bajo'), ('MEDIUM', 'Medio'), ('HIGH', 'Alto'), ('CRITICAL', 'Crítico')], default='MEDIUM', max_length=10),
        ),
    ]
