# Generated by Django 6.0.7 on 2026-07-13 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_risk_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='curve_a',
            field=models.FloatField(default=-1),
        ),
        migrations.AddField(
            model_name='event',
            name='curve_b',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='event',
            name='curve_c',
            field=models.FloatField(default=100),
        ),
    ]
